/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego_snake;

/**
 *
 * @author HUAWEI
 */
public class Instrucciones extends javax.swing.JFrame {

    /**
     * Creates new form Instrucciones
     */
    public Instrucciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Intrucciones = new javax.swing.JTextArea();
        Boton_atrasIns = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Intrucciones.setEditable(false);
        Intrucciones.setBackground(new java.awt.Color(102, 255, 102));
        Intrucciones.setColumns(20);
        Intrucciones.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Intrucciones.setForeground(new java.awt.Color(0, 0, 0));
        Intrucciones.setRows(5);
        Intrucciones.setText("El juego de Snake es un clásico juego de arcade en el que controlas una serpiente que se mueve por la pantalla. \nEl objetivo del juego es hacer crecer la serpiente tanto como sea posible sin chocar contra las paredes o contra\n su propio cuerpo.\n\nAquí tienes las instrucciones básicas de cómo se juega al Snake:\n\n1. Control de la serpiente: La serpiente se mueve en línea recta y puedes controlar su dirección utilizando las teclas\n de flecha del teclado (arriba, abajo, izquierda, derecha). Dependiendo de la versión del juego, también puede ser\n posible usar las teclas \"W\", \"A\", \"S\" y \"D\" para controlar la serpiente.\n\n2. Crecimiento de la serpiente: En la pantalla habrá una serie de puntos o alimentos que la serpiente debe comer \npara crecer. Cada vez que la serpiente come uno de estos puntos, crece un segmento más en su cuerpo.\n\n3. Evitar obstáculos: El juego tiene límites en el área de juego, generalmente representados por las paredes de la \npantalla. Si la serpiente choca contra una pared, el juego termina. También debes evitar chocar contra tu propio\n cuerpo, ya que esto también hará que pierdas.\n\n4. Puntuación y objetivo: El objetivo del juego es obtener la mayor puntuación posible. Puedes hacerlo comiendo \nlos puntos para hacer crecer tu serpiente. Cuanto más crezca, más difícil será evitar chocar contra las paredes y tu \npropio cuerpo.\n\n5. Dificultad: En la mayoría de las versiones de Snake, a medida que la serpiente crece, la velocidad del juego\n aumenta, lo que hace que sea más desafiante controlarla.\n\nRecuerda que las instrucciones pueden variar ligeramente dependiendo de la versión específica del juego de Snake\n que estés jugando. Sin embargo, en esencia, el objetivo es el mismo: hacer crecer la serpiente tanto como sea \nposible sin chocar. ¡Diviértete jugando al Snake!");
        Intrucciones.setBorder(null);
        jScrollPane2.setViewportView(Intrucciones);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 690, 340));

        Boton_atrasIns.setText("Volver");
        Boton_atrasIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_atrasInsActionPerformed(evt);
            }
        });
        jPanel1.add(Boton_atrasIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCCIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 310, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_atrasInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_atrasInsActionPerformed
        Menu_Snake volver = new Menu_Snake();
        volver.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_Boton_atrasInsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_atrasIns;
    private javax.swing.JTextArea Intrucciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
